class isFactionAdvanced {};
class craftedTransitInitialize { };
class craftedTransitDeactivate {};
class craftedTransitActivate {};
class getLoadoutPresets { };
class getArsenalItems { };
class loadCustomLoadout { };
class saveCustomLoadout { };
class registerPrisonnerCargoBox { };
class registerAttachAceOffset { };
class registerMedicalBox { };
class turnCivilianEnemy { };
class getFactionVehicles { };
class loadStaticAce { };
class setStaticAce { };
class createStaticAcePointsFromTrigger { };
class compileStaticAcePointsFromTriggers { };
class loadPowerTransformers { };
class getObjectiveCodenames { };
class countPlayerMinorRoles { };
class applyRoleToPlayer { };
class isCurrentPlayerMajorRole { };
class isCurrentPlayerMinorRole { };
class hasPlayerMajorRole { };
class hasPlayerMinorRole { };
class convertToPriceString { };
class getFortificationItems { };
class getCampCodenames { };
class registerEverPresentCamp { };
class getCursorTarget { };

class wildEnemyAttackSector { };
class blowTheShitUp { };
class blowTheShitUps { };
class loadPowerline { };
class applyHealToGroupOfPlayer { };
class hackerApplyTrojanHorse { };
class hackerApplySpyware { };

class aoGenerateBuildingLayouts {};
class aoStartGenerator {};
class aoActivateCombatZone {};
class aoDeactivateCombatZone {};
class aoActivateBuilding {};
class aoDeactivateBuilding {};
class aoSelectGarrisonPositions {};
class aoClearCombatZone {};

class aoStartSpawning {};
class getFactionUnit {};
class getFactionCertificationInsigna {};
