class isFactionAdvanced {};
class craftedTransitInitialize { };
class craftedTransitDeactivate {};
class craftedTransitActivate {};
class voiceInitialize { };
class voiceSelectFromHashMap { };
class voiceSelectRandomLine { };
class getLoadoutPresets { };
class getArsenalItems { };
class loadCustomLoadout { };
class saveCustomLoadout { };
class registerPrisonnerCargoBox { };
class registerAttachAceOffset { };
class registerMedicalBox { };
class getEnemyVehicle { };
class turnCivilianEnemy { };
class getFactionVehicles { };
class loadStaticAce { };
class setStaticAce { };
class createStaticAcePointsFromTrigger { };
class compileStaticAcePointsFromTriggers { };
class loadPowerTransformers { };
class loadPowerline { };
class getObjectiveCodenames { };
class countPlayerMinorRoles { };
class applyRoleToPlayer { };
class isCurrentPlayerMajorRole { };
class isCurrentPlayerMinorRole { };
class hasPlayerMajorRole { };
class hasPlayerMinorRole { };
class convertToPriceString { };
class getFortificationItems { };
class getCampCodenames { };
class registerEverPresentCamp { };
class getCursorTarget { };
class keybindCommandYouAlive { };
class keybindCommandEscort { };
class keybindCommandSurrender { };
class setSurrender { };
class keybindCommandDrag { };
class wildEnemyAttackSector { };
class blowTheShitUp { };
class blowTheShitUps { };
class powerlinesShutdown { };
class powerlineShutdown { };
class applyHealToGroupOfPlayer { };
class hackerApplyTrojanHorse { };
class hackerApplySpyware { };
class updateZeusCurator { };
class getRelatedPosition {};
class aoGenerateBuildingLayouts {};
class aoStartGenerator {};
class aoActivateCombatZone {};
class aoDeactivateCombatZone {};
class aoActivateBuilding {};
class aoDeactivateBuilding {};
class aoSelectGarrisonPositions {};
class aoClearCombatZone {};
class aoSpawnCivilianPatrol {};
class aoSpawnEnemyPatrol {};
class aoStartSpawning {};
class getFactionUnit {};
class getFactionCertificationInsigna {};
class commonSleepFPSBased {};
class commonEdenConditionalAttribute{};
class commonRelPosObject {};
class commonGetRelPosRotObject {};
class commonInitialUnitFaction {};

class commonUnitSetLoadout {};
class commonGetRandomFace {};
class commonGetRandomVoice {};
